# Configure an admin instance with jenkins and asgard.
- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - aws
    - edx_ansible
    - user
    - jenkins_admin
    - hotg
    - alton
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
