---

- name: install read-only ssh key
  copy: >
    content="{{ ANALYTICS_API_GIT_IDENTITY }}" dest={{ analytics_api_git_identity_file }}
    owner={{ analytics_api_user }} group={{ analytics_api_user }} mode=0600

- name: checkout code
  git: >
    dest={{ analytics_api_code_dir }} repo={{ analytics_api_source_repo }} version={{ ANALYTICS_API_VERSION }}
    accept_hostkey=yes
    ssh_opts="{{ analytics_api_git_ssh_opts }}"
  register: analytics_api_code_checkout
  notify: "restart the analytics service"
  sudo_user: "{{ analytics_api_user }}"

- name: write out app config file
  template: >
    src=edx/app/analytics-api/analytics-api.yaml.j2
    dest={{ COMMON_CFG_DIR  }}/{{ analytics_api_service_name }}.yaml
    mode=0644 owner={{ analytics_api_user }} group={{ analytics_api_user }}
  notify: restart the analytics service

- name: run collectstatic
  shell: >
    chdir={{ analytics_api_code_dir }}
    {{ analytics_api_venv_bin }}/python manage.py collectstatic --settings analyticsdataserver.settings.production --noinput --settings analyticsdataserver.settings.production
  sudo_user: "{{ analytics_api_user }}"
  environment:
    ANALYTICS_API_CFG: "{{ COMMON_CFG_DIR  }}/{{ analytics_api_service_name }}.yaml"

- name: install application requirements
  pip: >
    requirements="{{ analytics_api_requirements_base }}/{{ item }}"
    virtualenv="{{ analytics_api_venv_dir }}" state=present
  sudo_user: "{{ analytics_api_user }}"
  notify: restart the analytics service
  with_items: analytics_api_requirements

- name: write out the supervisior wrapper
  template: >
    src=edx/app/analytics-api/analytics-api.sh.j2
    dest={{ analytics_api_app_dir }}/{{ analytics_api_service_name }}.sh
    mode=0650 owner={{ supervisor_user }} group={{ common_web_user }}
  notify: restart the analytics service

- name: write supervisord config
  template: >
    src=edx/app/supervisor/conf.d.available/analytics-api.conf.j2
    dest="{{ supervisor_available_dir }}/{{ analytics_api_service_name }}.conf"
    owner={{ supervisor_user }} group={{ common_web_user }} mode=0644
  notify: restart the analytics service

- name: enable supervisor script
  file: >
    src={{ supervisor_available_dir }}/{{ analytics_api_service_name }}.conf
    dest={{ supervisor_cfg_dir }}/{{ analytics_api_service_name }}.conf
    state=link
    force=yes
  notify: restart the analytics service
  when: not disable_edx_services

- name: update supervisor configuration
  shell: "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  when: not disable_edx_services

- name: remove read-only ssh key for the content repo
  file: path={{ analytics_api_git_identity_file }} state=absent
