- hosts: tag_Name_jumpbox_prod
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/users_jumpbox.yml"
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir:  '../../../configuration-secure/ansible/local'
  roles:
    - common
    - supervisor
    - role: gh_users
      gh_users:
        - sefk
        - jbau
        - jrbl
        - ali123
        - caesar2164
        - dcadams
        - nparlante
      gh_users_no_sudo:
        - jinpa
        - gbruhns
        - paepcke
        - akshayak
      tags: users
